### ISSUE TITLE
Crash with empty table cell

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/notion-markdown-cms#1]
![image](https://user-images.githubusercontent.com/14248574/149917740-78886010-1807-4847-aa9c-5f1cd8bf994c.png)

This Notion page (or table?) crashes on the `link` property after doing some manual console.log debugging. Not sure if this is intended or not?

The line that crashed it is line 20 in `DatabaseTableRender.ts`

```
TypeError: Cannot read property 'toString' of null
    at Function.escapeTableCell (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/DatabaseTableRenderer.ts:32:20)
    at /home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/DatabaseTableRenderer.ts:15:31
    at Array.map (<anonymous>)
    at DatabaseTableRenderer.renderTable (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/DatabaseTableRenderer.ts:14:62)
    at ChildDatabaseRenderer.renderChildDatabase (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/ChildDatabaseRenderer.ts:47:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeferredRenderer.renderChildDatabase (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/DeferredRenderer.ts:37:12)
    at async BlockRenderer.renderBlock (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/BlockRenderer.ts:130:20)
    at async RecursiveBodyRenderer.renderBlock (/home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/RecursiveBodyRenderer.ts:42:25)
    at async /home/runner/work/cloudfoundation/cloudfoundation/node_modules/@meshcloud/notion-markdown-cms/src/RecursiveBodyRenderer.ts:27:20
```

**Comment by JohannesRudolph** [comment]
This should be fixed, will now simply emit an empty cell
